In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/lib/python3.11/site-packages/numpy/__init__.py'>

Creating Arrays

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
a[2] = 10

In [12]:
a

array([ 1,  2, 10,  4,  5,  6,  7])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Multi-dimentional arrays

In [17]:
# np.zeroes((5,2)) removed in 1.25.0

In [19]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [20]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
print(n[0][1])

2


In [24]:
n[0][1] = 20

In [25]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [26]:
n[0]

array([ 1, 20,  3])

In [27]:
n[:, 2] = [1, 1, 1]

In [28]:
n

array([[ 1, 20,  1],
       [ 4,  5,  1],
       [ 7,  8,  1]])

Randomly generated arrays

In [35]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [34]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [36]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

Element-wise operations

In [37]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [38]:
a + 1

array([1, 2, 3, 4, 5])

In [39]:
b = (10 + (a * 2)) ** 2 / 100

In [40]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [41]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [42]:
a / b

array([0.        , 0.69444444, 1.02040816, 1.171875  , 1.2345679 ])

Comparison Operations

In [43]:
a

array([0, 1, 2, 3, 4])

In [44]:
a >= 2

array([False, False,  True,  True,  True])

In [45]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [46]:
a > b

array([False, False,  True,  True,  True])

In [47]:
a[a > b]

array([2, 3, 4])

Summarizing Operations

In [48]:
a

array([0, 1, 2, 3, 4])

In [49]:
a.std()

1.4142135623730951

In [50]:
n.min()

1